name       : meson-python
version    : 0.14.0
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/m/meson_python/meson_python-0.14.0.tar.gz : b96866690326544dfe452583753ac3f43313227e9fd9416701a8df90af212234
homepage   : https://github.com/mesonbuild/meson-python
license    : MIT
component  : programming.python
summary    : Meson PEP 517 Python build backend 
description: |
    meson-python is a Python build backend built on top of the Meson build system. It enables to use Meson for the configuration and build steps of Python packages. Meson is an open source build system meant to be both extremely fast, and, even more importantly, as user friendly as possible. meson-python is best suited for building Python packages containing extension modules implemented in languages such as C, C++, Cython, Fortran, Pythran, or Rust.
builddeps  :
    - python-build
    - python-installer
    - python-pyproject-metadata
rundeps    :
    - meson
    - python-tomli
    - python-pyproject-metadata
build      : |
    %python3_setup
install    : |
    %python3_install
